export interface IndustryData {
  slug: string;
  name: string;
  displayName: string;
  descriptors: string[];
  nouns: string[];
  suffixes: string[];
  intro: string;
  examples: string[];
  faqs: { question: string; answer: string }[];
}

export const INDUSTRIES: Record<string, IndustryData> = {
  bakery: {
    slug: 'bakery',
    name: 'bakery',
    displayName: 'Bakery',
    descriptors: ['fresh', 'golden', 'rustic', 'artisan', 'sweet', 'sunrise', 'crust', 'hearth', 'honey', 'warm'],
    nouns: ['bakery', 'oven', 'loaf', 'crumb', 'bread', 'pastry', 'kitchen', 'bake', 'crust', 'dough'],
    suffixes: ['Co', 'House', 'Works', 'Studio', '& Co', 'Collective', 'Place'],
    intro: 'Naming your bakery is one of the most delicious creative challenges you\'ll face as a business owner. A great bakery name should evoke warmth, freshness, and the irresistible smell of bread coming out of the oven. Whether you\'re opening a classic French patisserie, a sourdough-focused artisan bakery, or a modern cake design studio, your business name sets the tone for the experience customers can expect. The best bakery names are short, memorable, and paint a vivid picture. Think of names that suggest craftsmanship — words like "artisan," "hearth," or "golden" immediately communicate quality and tradition. Alternatively, a playful or unique name can help your bakery stand out in a crowded market. Consider your target audience: a neighborhood family bakery might want something warm and approachable, while a high-end patisserie might prefer something elegant and refined.',
    examples: ['Golden Crumb Bakery', 'The Artisan Loaf', 'Sunrise Pastry Co', 'Hearth & Honey', 'Rustic Oven House'],
    faqs: [
      { question: 'What makes a good bakery name?', answer: 'A good bakery name is memorable, easy to pronounce, and evokes feelings of warmth, freshness, and quality. It should reflect your bakery\'s personality — whether that\'s artisan and traditional, modern and trendy, or playful and family-friendly.' },
      { question: 'Should my bakery name describe what I sell?', answer: 'Not necessarily. Some of the most successful bakeries have abstract or creative names. However, including baking-related words can help customers immediately understand what you do and improve your local SEO rankings.' },
      { question: 'How do I check if a bakery name is taken?', answer: 'Search your state\'s business registry, check the USPTO trademark database, and search for the domain name availability. Also check social media handles to ensure consistency across platforms.' },
      { question: 'Can I use my name for my bakery?', answer: 'Absolutely — using your own name (like "Smith\'s Bakery") is a classic approach that adds a personal touch. It works especially well for high-end custom cake businesses where your personal brand is the product.' },
    ],
  },
  consulting: {
    slug: 'consulting',
    name: 'consulting',
    displayName: 'Consulting',
    descriptors: ['strategic', 'apex', 'summit', 'core', 'prime', 'vertex', 'clarity', 'insight', 'nexus', 'pinnacle'],
    nouns: ['partners', 'advisory', 'consulting', 'group', 'collective', 'solutions', 'ventures', 'capital'],
    suffixes: ['LLC', 'Co', 'Partners', 'Group', 'Associates', 'Advisors'],
    intro: 'Your consulting firm\'s name is a critical part of your brand identity — it signals expertise, trustworthiness, and the value you bring to clients. The consulting industry is highly competitive, and a strong business name can help you stand out from hundreds of similar firms. The best consulting names often combine a sense of authority with clarity of purpose. Words like "strategy," "apex," "summit," and "clarity" signal high-level thinking and results-orientation. Many successful consulting firms use founder names (McKinsey, Deloitte) or evocative single words that suggest expertise and insight. When naming your consulting business, think about your niche: a management consulting firm has different naming needs than an IT consultancy or a marketing strategy firm. Consider your target clients — Fortune 500 companies respond to different names than small businesses do.',
    examples: ['Apex Strategy Group', 'Summit Advisory Partners', 'Clarity Consulting Co', 'Nexus Advisors', 'Pinnacle Partners LLC'],
    faqs: [
      { question: 'Should consulting firm names include "consulting" in the name?', answer: 'Including "consulting" or "advisory" makes your service immediately clear, which is valuable for SEO and first impressions. However, many top firms omit it for a more prestigious, minimalist feel.' },
      { question: 'What words convey credibility in consulting names?', answer: 'Words like "apex," "summit," "strategy," "advisory," "partners," and "group" tend to convey authority and expertise. Geographic names can also add prestige for locally-focused firms.' },
      { question: 'Should I use my own name for my consulting firm?', answer: 'Using your name works well if you have personal brand recognition in your industry. It\'s common in boutique consulting. However, it can make the firm harder to sell or transition if you plan to scale.' },
      { question: 'How important is the domain name for a consulting firm?', answer: 'Very important. Your website is often the first impression. Aim for a .com domain that closely matches your business name. If the exact match isn\'t available, consider adding "consulting" or your location.' },
    ],
  },
  cleaning: {
    slug: 'cleaning',
    name: 'cleaning',
    displayName: 'Cleaning',
    descriptors: ['spotless', 'sparkling', 'pristine', 'fresh', 'gleam', 'bright', 'clean', 'pure', 'shine', 'crisp'],
    nouns: ['cleaning', 'services', 'solutions', 'crew', 'team', 'pros', 'masters', 'specialists'],
    suffixes: ['Co', 'LLC', 'Services', 'Group', 'Pro'],
    intro: 'Naming your cleaning business requires striking the right balance between professionalism and approachability. Your name should instantly communicate cleanliness, reliability, and trustworthiness — qualities that clients prioritize when inviting someone into their home or office. Great cleaning business names often use words that evoke cleanliness directly: "spotless," "pristine," "sparkling," or "gleam" create an immediate visual association with a clean, fresh environment. For a residential cleaning service, a warm and friendly name can be reassuring to homeowners. For commercial cleaning companies, a more professional tone with words like "solutions" or "services" may be more appropriate. Location-based names can also work well for local SEO, helping you appear in "cleaning service near me" searches.',
    examples: ['Spotless Solutions LLC', 'Sparkling Clean Pro', 'Pristine Home Services', 'Gleam Cleaning Co', 'Fresh Start Cleaners'],
    faqs: [
      { question: 'What should I include in a cleaning business name?', answer: 'Consider including words that evoke cleanliness (spotless, gleam, pristine), your service area, or your specialty (residential, commercial, deep cleaning). Avoid names that are too generic or hard to spell.' },
      { question: 'Should my cleaning business name include my location?', answer: 'Including your city or region can boost local SEO and help potential clients immediately know you serve their area. However, it can limit your brand if you expand to new locations later.' },
      { question: 'How long should a cleaning company name be?', answer: 'Shorter names (2-3 words) are generally easier to remember and look better on uniforms, vehicles, and signage. Avoid anything longer than 4-5 words.' },
      { question: 'Can I use my personal name for a cleaning business?', answer: 'Yes, many successful cleaning businesses use the owner\'s name (e.g., "Maria\'s Cleaning Services"). It adds a personal touch and can build trust with residential clients who value knowing who\'s in their home.' },
    ],
  },
  'coffee-shop': {
    slug: 'coffee-shop',
    name: 'coffee-shop',
    displayName: 'Coffee Shop',
    descriptors: ['brew', 'roast', 'grounds', 'bean', 'espresso', 'drip', 'steep', 'bold', 'rich', 'daily'],
    nouns: ['coffee', 'cafe', 'roasters', 'brew', 'cup', 'grind', 'press', 'bar', 'house'],
    suffixes: ['Co', 'House', 'Bar', 'Studio', 'Collective', 'Corner'],
    intro: 'Your coffee shop\'s name is the first thing customers will taste before they even enter your door. A great coffee shop name should be inviting, memorable, and reflect the unique atmosphere and culture of your space. Whether you\'re opening a cozy neighborhood cafe, a specialty third-wave coffee bar, or a drive-through espresso stand, the right name will attract your target customers and build brand loyalty. Coffee shop names often draw from coffee terminology (brew, roast, grounds, espresso) or create an evocative atmosphere (cozy, artisan, community). Think about the experience you want to create: a study-friendly cafe might emphasize calm and focus, while a social gathering space might emphasize community and warmth.',
    examples: ['Bold Brew Co', 'The Daily Grind House', 'Roast & Co Coffee', 'Steep Street Cafe', 'Bean & Bar Collective'],
    faqs: [
      { question: 'What makes a memorable coffee shop name?', answer: 'Memorable coffee shop names are short, easy to pronounce, and evoke the experience of great coffee or a welcoming atmosphere. Playing with coffee terminology or creating a sense of place works well.' },
      { question: 'Should my coffee shop name include "coffee" or "cafe"?', answer: 'Including coffee-related words helps with discoverability, especially in local searches. However, many iconic cafes use abstract names that become synonymous with their brand over time.' },
      { question: 'How do I come up with a unique coffee shop name?', answer: 'Start with words that describe your shop\'s vibe, your coffee sourcing story, or your neighborhood. Combine unexpected words, use alliteration, or play on coffee puns for something memorable and shareable.' },
      { question: 'Are puns good for coffee shop names?', answer: 'Coffee puns can be charming and memorable for casual, neighborhood cafes. Names like "Grounds for Celebration" or "Daily Grind" create instant connection. However, they may feel less appropriate for high-end specialty roasters.' },
    ],
  },
  'tech-startup': {
    slug: 'tech-startup',
    name: 'tech-startup',
    displayName: 'Tech Startup',
    descriptors: ['next', 'nova', 'spark', 'swift', 'flux', 'grid', 'edge', 'core', 'apex', 'pixel'],
    nouns: ['tech', 'labs', 'systems', 'digital', 'cloud', 'data', 'stack', 'code', 'app', 'io'],
    suffixes: ['.io', 'HQ', 'Labs', 'AI', 'Tech', 'Works'],
    intro: 'Naming your tech startup is one of the most exciting — and challenging — parts of launching your company. A great tech company name should be short, memorable, and scalable as your company grows. The best tech startup names are often abstract (Google, Apple, Amazon) or combine familiar words in unexpected ways (Facebook, Twitter, Slack). Your name will appear in press releases, product names, app stores, and investor pitch decks — it needs to work everywhere. For tech startups, domain availability is crucial: a .com or .io domain matching your brand name is essential. Many startups choose names that are easy to spell, pronounce in any language, and can be trademarked.',
    examples: ['NovaSpark Labs', 'FluxGrid Systems', 'EdgeCore HQ', 'SwiftStack Tech', 'PixelApex AI'],
    faqs: [
      { question: 'What makes a good tech startup name?', answer: 'Great tech startup names are typically short (1-2 syllables), easy to spell and pronounce, unique enough to trademark, and either abstract or suggestive of speed, intelligence, or innovation.' },
      { question: 'Should my startup name end in ".io"?', answer: '.io domains are popular in the tech community and signal a tech-oriented brand. However, .com remains the most trusted TLD. If you can get yourname.com, that\'s typically the better choice.' },
      { question: 'How important is trademark availability for a startup name?', answer: 'Extremely important. Search the USPTO database before committing to a name. A trademark conflict can force an expensive rebrand after you\'ve already built brand recognition.' },
      { question: 'Should my startup name describe what it does?', answer: 'Descriptive names (like "Slack" suggesting communication or "Zoom" suggesting speed) can be helpful early on. But many of the most successful tech brands have abstract names that become associated with their product through marketing.' },
    ],
  },
  fitness: {
    slug: 'fitness',
    name: 'fitness',
    displayName: 'Fitness',
    descriptors: ['peak', 'forge', 'power', 'iron', 'pulse', 'drive', 'lift', 'strong', 'fuel', 'grind'],
    nouns: ['fitness', 'gym', 'training', 'performance', 'athletic', 'strength', 'studio', 'lab', 'hub'],
    suffixes: ['Co', 'Studio', 'Lab', 'HQ', 'Pro', 'Club'],
    intro: 'Naming your fitness business sets the tone for the intensity, community, and culture you\'re building. Whether you\'re opening a CrossFit-style box, a yoga studio, a personal training practice, or a boutique fitness studio, your name should motivate your target clients and differentiate you from the crowded fitness market. The best fitness business names convey energy, transformation, and results. Words like "peak," "forge," "pulse," and "elevate" suggest challenge and achievement. Consider who your ideal client is: a women\'s empowerment gym might choose a different name than a hardcore powerlifting club. Your fitness brand name will appear on merchandise, signage, social media, and in Google searches — make it count.',
    examples: ['Peak Performance Studio', 'IronForge Fitness', 'Pulse Athletic Club', 'Drive Training Lab', 'Strong Ground Gym'],
    faqs: [
      { question: 'What words work well in fitness business names?', answer: 'Words that evoke strength, movement, transformation, and community work well: peak, forge, pulse, elevate, grind, iron, power, fuel. Avoid overly generic terms like "fitness center" without something unique attached.' },
      { question: 'Should my gym include my location in the name?', answer: 'Including your neighborhood or city can help with local SEO and gives a sense of community. It works well for boutique studios focused on a specific area, but may limit expansion later.' },
      { question: 'How do I differentiate my fitness brand name?', answer: 'Focus on your unique training methodology, target demographic, or the transformation you promise. A boxing gym for women, a functional fitness studio for seniors, or a high-performance athletic training center each warrant different naming approaches.' },
      { question: 'Should a personal trainer use their own name or a brand name?', answer: 'Personal trainers often start with their own name (e.g., "John Smith Fitness") for authenticity, then create a separate brand name as they grow. A distinct brand name makes it easier to hire other trainers and scale.' },
    ],
  },
  'yoga-studio': {
    slug: 'yoga-studio',
    name: 'yoga-studio',
    displayName: 'Yoga Studio',
    descriptors: ['serene', 'balance', 'flow', 'zen', 'lotus', 'breath', 'inner', 'still', 'arise', 'bloom'],
    nouns: ['yoga', 'studio', 'wellness', 'mindfulness', 'practice', 'center', 'sanctuary', 'space'],
    suffixes: ['Co', 'Studio', 'Center', 'Collective', 'Space', 'Sanctuary'],
    intro: 'A yoga studio name should reflect the peace, balance, and transformation that your practice offers. Whether you focus on power yoga, gentle restorative classes, hot yoga, or a mindfulness-based approach, your studio\'s name is the first impression your potential students will have. Great yoga studio names often draw from Sanskrit terminology, natural imagery, or concepts central to the practice like breath, balance, and flow. The name should feel calming yet inspiring — evoking the journey inward that yoga facilitates. Consider the energy of your studio: a vigorous power yoga studio might use more dynamic language, while a meditation and yin yoga center might favor softer, more contemplative words.',
    examples: ['Serene Flow Studio', 'Lotus Balance Center', 'Breath & Being Yoga', 'Inner Sanctuary Wellness', 'Arise Yoga Collective'],
    faqs: [
      { question: 'Should I use Sanskrit words in my yoga studio name?', answer: 'Sanskrit words can add authenticity and depth to a yoga studio name. Words like "shanti" (peace), "ananda" (bliss), or "prana" (breath) resonate with yogis. However, make sure they\'re easy for your target audience to pronounce and remember.' },
      { question: 'What mood should a yoga studio name convey?', answer: 'Yoga studio names typically convey calm, transformation, community, or mindfulness. The right tone depends on your style: power yoga studios can use more dynamic language, while restorative or meditation studios should evoke peace and stillness.' },
      { question: 'How long should a yoga studio name be?', answer: 'Two to three words is ideal for yoga studios. Short names are easier to remember and look cleaner on signage and social media. Avoid overly long, complicated names.' },
      { question: 'Can I use my own name for a yoga studio?', answer: 'Many successful yoga teachers build studios around their personal brand. Your name can work well, especially if you\'re a known teacher in your community. Consider combining your name with a descriptive word (e.g., "Sarah Chen Yoga" or "Chen Flow Studio").' },
    ],
  },
  photography: {
    slug: 'photography',
    name: 'photography',
    displayName: 'Photography',
    descriptors: ['focus', 'frame', 'lens', 'capture', 'light', 'vivid', 'still', 'flash', 'pixel', 'golden'],
    nouns: ['photography', 'studio', 'images', 'portraits', 'visuals', 'shots', 'lens', 'focus', 'capture'],
    suffixes: ['Co', 'Studio', 'Images', 'Photography', 'Visuals', 'Creative'],
    intro: 'Your photography business name should reflect your artistic vision, style, and the emotions you capture through your lens. Photography is an artistic and highly personal profession — your name is part of your brand story. Whether you specialize in weddings, portraits, commercial photography, newborns, or fine art, your name should speak to your ideal clients and differentiate your work. Many successful photographers use their own name for authenticity and personal branding, while others create a studio name that better reflects their aesthetic. Consider the words that describe your photography style: "golden hour," "vivid," "documentary," "fine art," or "storytelling" can all be incorporated into a memorable brand name.',
    examples: ['Golden Frame Studios', 'Focus & Light Photography', 'Vivid Lens Co', 'Capture Creative Studio', 'Still Moment Photography'],
    faqs: [
      { question: 'Should photographers use their own name or a business name?', answer: 'Both approaches work well. Using your own name builds personal brand recognition, which is valuable in photography. A separate studio name can feel more professional for commercial work and makes it easier to hire additional photographers.' },
      { question: 'What style should a photography business name convey?', answer: 'Your name should match your photography style and target market. Wedding photographers might want something romantic and timeless; commercial photographers something sleek and professional; lifestyle photographers something warm and authentic.' },
      { question: 'How important is Instagram handle availability for a photography business?', answer: 'Very important. Photography is a visual medium and Instagram is a primary marketing channel. Check handle availability before finalizing your name to ensure consistency across platforms.' },
      { question: 'Can I change my photography business name later?', answer: 'Yes, but rebranding can be costly and confusing. It\'s worth investing time upfront to choose a name you can grow with. That said, many photographers successfully rebrand as their style and target market evolves.' },
    ],
  },
  'clothing-boutique': {
    slug: 'clothing-boutique',
    name: 'clothing-boutique',
    displayName: 'Clothing Boutique',
    descriptors: ['chic', 'luxe', 'velvet', 'silk', 'thread', 'stitch', 'noir', 'bloom', 'grace', 'style'],
    nouns: ['boutique', 'fashion', 'style', 'threads', 'wardrobe', 'closet', 'label', 'collection', 'atelier'],
    suffixes: ['Co', 'Boutique', 'Studio', 'Label', 'Collection', 'Atelier'],
    intro: 'A clothing boutique name is a critical part of your fashion brand identity — it\'s the first thing shoppers see, and it communicates your aesthetic, price point, and personality instantly. Whether you\'re curating vintage finds, designing your own label, or offering contemporary women\'s fashion, your boutique name should resonate with your target customer and reflect the style of clothing you sell. Fashion names often draw on luxury language (velvet, silk, luxe), emotional concepts (grace, bloom, noir), or play with fashion terminology. Think about the customer experience you create: a boho-chic boutique has very different naming needs than a minimalist contemporary label or a plus-size inclusive fashion store.',
    examples: ['Velvet Thread Boutique', 'Chic Label Co', 'Silk & Style Atelier', 'Noir Fashion Studio', 'Bloom Wardrobe'],
    faqs: [
      { question: 'What makes a good boutique name?', answer: 'A good boutique name is distinctive, easy to remember, and reflects your fashion aesthetic. It should appeal to your target customer\'s aspirations and self-image. Luxury boutiques use sophisticated language; casual boutiques can be more playful.' },
      { question: 'Should a clothing boutique name include the type of clothing?', answer: 'Including general terms like "boutique," "fashion," or "style" helps with discoverability. However, being too specific (e.g., "women\'s dresses") can limit your brand as your inventory evolves.' },
      { question: 'How do I check if a boutique name is available?', answer: 'Check your state business registry, USPTO trademark database, domain availability, and social media handles. Fashion is a competitive industry — ensure your name is truly unique before investing in branding.' },
      { question: 'Can I name my boutique after myself?', answer: 'Using your name is a classic approach in fashion (think Coco Chanel, Ralph Lauren). It works especially well if you\'re a designer or have personal style recognition. It adds authenticity and makes the brand feel curated and personal.' },
    ],
  },
  restaurant: {
    slug: 'restaurant',
    name: 'restaurant',
    displayName: 'Restaurant',
    descriptors: ['savory', 'rustic', 'harvest', 'ember', 'kitchen', 'table', 'farm', 'local', 'craft', 'salt'],
    nouns: ['kitchen', 'table', 'bistro', 'grill', 'eatery', 'dining', 'restaurant', 'house', 'room', 'bar'],
    suffixes: ['Co', 'House', 'Kitchen', 'Bistro', 'Bar & Grill', '& Co'],
    intro: 'Your restaurant\'s name is the beginning of the dining experience — it sets expectations for the atmosphere, cuisine style, and price point before a single dish is served. Great restaurant names are evocative, memorable, and reflect the unique character of your establishment. Whether you\'re opening a farm-to-table bistro, a casual family restaurant, a fine dining establishment, or an ethnic cuisine spot, your name should tell a story. The most successful restaurant names often reference the cuisine, the atmosphere, or the chef\'s philosophy. Consider names that evoke the sensory experience of dining: warmth, flavor, community, and craftsmanship are themes that resonate with diners looking for more than just a meal.',
    examples: ['The Ember Table', 'Harvest Kitchen Co', 'Rustic Salt Bistro', 'Farm & Table House', 'Salt & Craft Kitchen'],
    faqs: [
      { question: 'What should I consider when naming my restaurant?', answer: 'Consider your cuisine type, target demographic, price point, and the atmosphere you want to create. A fine dining restaurant and a casual eatery have very different naming needs. Also think about SEO — including your cuisine type can help with local search visibility.' },
      { question: 'Should restaurant names be funny or serious?', answer: 'It depends entirely on your concept. A playful name works great for casual dining, food trucks, and burger joints. Fine dining and upscale concepts usually benefit from more elegant, serious names.' },
      { question: 'How important is it to include the cuisine type in a restaurant name?', answer: 'Including the cuisine type (Italian, sushi, BBQ, etc.) helps with local SEO and immediate customer understanding. However, many iconic restaurants use abstract names that become synonymous with their cuisine through reputation.' },
      { question: 'Can I use my family name for a restaurant?', answer: 'Absolutely — family names create a sense of heritage and personal investment that diners love. "Mama Rosa\'s," "The Johnson Table," or simply "[Family Name]\'s" communicate authenticity and tradition.' },
    ],
  },
  'hair-salon': {
    slug: 'hair-salon',
    name: 'hair-salon',
    displayName: 'Hair Salon',
    descriptors: ['sleek', 'luxe', 'radiant', 'chic', 'gloss', 'trim', 'silk', 'velvet', 'shear', 'blade'],
    nouns: ['salon', 'studio', 'lounge', 'bar', 'house', 'cuts', 'style', 'look', 'hair'],
    suffixes: ['Co', 'Studio', 'Lounge', 'Bar', 'Collective', 'Suite'],
    intro: 'Naming your hair salon requires capturing the transformation, luxury, and personal care experience that clients are paying for. A great salon name should feel inviting, professional, and reflect your salon\'s style — whether that\'s a high-end color studio, a quick-service cuts bar, a natural hair specialist, or a full-service luxury spa salon. Salon names often play with hair-related terminology (shear, trim, gloss, silk) or evoke luxury and beauty (radiant, luxe, velvet). Think about your target clientele and the experience they\'re seeking. A trendy urban salon serving millennials has different naming needs than a classic barbershop or a upscale color correction specialist.',
    examples: ['Sleek Studio Salon', 'The Gloss Bar', 'Radiant Shear Co', 'Velvet Cuts Lounge', 'Luxe Hair Suite'],
    faqs: [
      { question: 'What makes a good hair salon name?', answer: 'A good hair salon name is memorable, reflects your service style and target market, and is easy to find online. It should convey the experience clients can expect — whether that\'s luxury, speed, expertise in natural hair, or creative coloring.' },
      { question: 'Should I include "salon" or "studio" in my business name?', answer: 'Including a descriptor like "salon," "studio," or "bar" helps with immediate clarity and local SEO. "Studio" and "bar" feel more modern; "salon" is classic and widely understood.' },
      { question: 'How do stylists choose between using their name vs. a brand name?', answer: 'Many stylists start with their name for personal brand building, then create a separate salon name when they open a space. Using your name works if you\'re building a reputation-based clientele; a brand name is better if you plan to hire and scale.' },
      { question: 'What are some naming trends in the salon industry?', answer: 'Current trends include using "bar" (blowout bar, color bar), minimalist single-word names, or names that suggest a specific specialty (balayage, Brazilian blowout, natural hair). Location-based names also remain popular for neighborhood salons.' },
    ],
  },
  'real-estate': {
    slug: 'real-estate',
    name: 'real-estate',
    displayName: 'Real Estate',
    descriptors: ['prime', 'premier', 'prestige', 'landmark', 'apex', 'summit', 'heritage', 'key', 'crown', 'estate'],
    nouns: ['realty', 'properties', 'real estate', 'homes', 'group', 'partners', 'ventures', 'investments'],
    suffixes: ['LLC', 'Group', 'Partners', 'Realty', 'Properties', '& Associates'],
    intro: 'A real estate business name needs to communicate trustworthiness, expertise, and market knowledge. Whether you\'re an independent agent, starting a boutique brokerage, or launching a property investment firm, your name will appear on yard signs, business cards, and marketing materials viewed by people making the biggest financial decisions of their lives. The best real estate business names convey stability, professionalism, and local expertise. Words like "premier," "heritage," "landmark," and "prestige" signal high-end positioning, while "keys," "home," and "community" create a more approachable feel. Many real estate professionals use their own name combined with "Realty," "Properties," or "Group" for instant credibility.',
    examples: ['Premier Property Group', 'Landmark Realty Partners', 'Heritage Homes LLC', 'Apex Real Estate', 'Crown Properties & Associates'],
    faqs: [
      { question: 'Should a real estate business include a location in the name?', answer: 'Including your market area (city, neighborhood, or region) is extremely valuable for local SEO and immediate client understanding. "Downtown Realty" or "Coastal Properties" signals expertise in a specific area.' },
      { question: 'What words convey trust in real estate business names?', answer: 'Words like "premier," "trusted," "heritage," "cornerstone," and "landmark" convey stability and trustworthiness. Client-focused words like "home" and "keys" create an approachable, helpful image.' },
      { question: 'How do real estate agents typically name their business?', answer: 'Most agents start with "[Name] Realty" or "[Name] Properties" for personal branding. As agents build teams, they often create a team name like "The [Name] Group" before potentially launching an independent brokerage.' },
      { question: 'Is it better to use a personal name or a brand name for real estate?', answer: 'Personal names build individual reputation, which is valuable in real estate where trust is paramount. Brand names are better for teams and brokerages. Many successful agents use both — a personal brand supported by a brokerage name.' },
    ],
  },
  'marketing-agency': {
    slug: 'marketing-agency',
    name: 'marketing-agency',
    displayName: 'Marketing Agency',
    descriptors: ['bold', 'vivid', 'sharp', 'creative', 'launch', 'signal', 'pulse', 'reach', 'impact', 'edge'],
    nouns: ['agency', 'media', 'creative', 'marketing', 'digital', 'brand', 'studios', 'group', 'collective'],
    suffixes: ['Co', 'Agency', 'Studios', 'Creative', 'Group', 'Media'],
    intro: 'Your marketing agency\'s name is your first and most important marketing campaign. It needs to communicate creativity, results, and expertise to potential clients who are trusting you to grow their business. A great agency name should be memorable, inspire confidence, and hint at the transformative impact you deliver. The best marketing agency names often combine energy with credibility: "bold," "signal," "impact," and "launch" suggest action and results, while "creative," "studio," and "media" establish the professional context. Think about your specialization: a social media agency, a branding firm, a performance marketing shop, and a full-service agency each have different personality requirements.',
    examples: ['Bold Signal Agency', 'Vivid Impact Media', 'Launch Creative Co', 'Edge Digital Group', 'Pulse Marketing Studio'],
    faqs: [
      { question: 'What makes a marketing agency name credible?', answer: 'Credibility comes from names that suggest expertise and results. Words like "strategy," "performance," "impact," and "growth" signal seriousness. Avoid overly clever puns that might undermine professionalism in a B2B context.' },
      { question: 'Should my agency name reflect its specialty?', answer: 'If you have a clear specialty (SEO, social media, branding), including a hint of it in your name helps attract the right clients. However, too specific a name can limit you if you expand your services.' },
      { question: 'How important is a creative name for a creative agency?', answer: 'Extremely important — your agency name is itself a demonstration of your creativity and branding ability. Clients will judge your creative skills partly based on how well you\'ve branded yourself.' },
      { question: 'Should I use my name for my marketing agency?', answer: 'Using your name works well for boutique consultancies and solo practitioners. For a team-based agency you plan to scale, a brand name is usually better as it doesn\'t tie the company\'s identity to one person.' },
    ],
  },
  construction: {
    slug: 'construction',
    name: 'construction',
    displayName: 'Construction',
    descriptors: ['solid', 'forge', 'stone', 'steel', 'build', 'iron', 'anchor', 'foundation', 'prime', 'craft'],
    nouns: ['construction', 'builders', 'contractors', 'build', 'group', 'works', 'services', 'co'],
    suffixes: ['LLC', 'Co', 'Inc', 'Group', 'Brothers', '& Sons', 'Construction'],
    intro: 'Naming your construction company requires projecting strength, reliability, and craftsmanship — the qualities clients look for when trusting you with their biggest investments. Whether you\'re a general contractor, a specialty trade (plumbing, electrical, roofing), or a residential homebuilder, your business name sets the tone for client relationships. The best construction company names evoke durability and expertise. Words like "foundation," "solid," "forge," "steel," and "stone" immediately communicate strength and permanence. Many construction companies use family names or geographic references to suggest roots in the community. Consider including your specialty if it\'s distinctive — it helps with both client understanding and local SEO.',
    examples: ['SteelForge Construction', 'Solid Foundation Builders', 'Stone & Iron Group', 'Anchor Build Co', 'CraftWorks Contractors LLC'],
    faqs: [
      { question: 'What words work well for construction company names?', answer: 'Words evoking strength and reliability work best: forge, foundation, solid, build, craft, stone, iron, anchor. These convey the durability and expertise clients expect from a construction company.' },
      { question: 'Should a construction company include a specialty in its name?', answer: 'If you specialize in a specific trade or type of construction (custom homes, commercial, roofing), including it in your name can attract the right clients. General contractors often prefer broader names to avoid limiting their scope.' },
      { question: 'Are family names good for construction businesses?', answer: 'Yes — family names (like "Johnson & Sons Construction") convey tradition, pride, and accountability in the construction industry. They suggest the owners\' reputation is personally on the line with every project.' },
      { question: 'How important is a professional image for a construction company name?', answer: 'Very important. Clients, especially commercial clients, are making large financial decisions. A professional name on your trucks, signage, and business cards builds confidence. Avoid overly casual or comedic names for construction businesses.' },
    ],
  },
  'pet-grooming': {
    slug: 'pet-grooming',
    name: 'pet-grooming',
    displayName: 'Pet Grooming',
    descriptors: ['fluffy', 'paw', 'waggle', 'happy', 'clean', 'fresh', 'pamper', 'sparkle', 'cozy', 'fuzzy'],
    nouns: ['grooming', 'pets', 'paws', 'tails', 'fur', 'salon', 'spa', 'studio'],
    suffixes: ['Co', 'Studio', 'Salon', 'Spa', 'Hub', 'Place'],
    intro: 'A pet grooming business name should be warm, approachable, and reflect the love and care you give to your four-legged clients. Pet owners are deeply attached to their animals and want to entrust their grooming to someone who clearly adores animals too. The best pet grooming business names are playful and fun while maintaining professionalism. Words like "paws," "fur," "fluffy," and "waggle" immediately signal a pet-focused business, while terms like "pamper," "spa," and "salon" communicate the level of care provided. Think about your unique selling proposition: mobile pet grooming, luxury dog spa services, or specialty cat grooming each warrant different naming approaches.',
    examples: ['Happy Paws Studio', 'Fluffy Friends Grooming', 'Pampered Pets Salon', 'Sparkle Fur Spa', 'Waggle & Clean Co'],
    faqs: [
      { question: 'What tone should a pet grooming business name have?', answer: 'Pet grooming names should feel warm, friendly, and loving — they need to reassure anxious pet owners that their beloved animals are in caring hands. Playful names with pet-related wordplay work particularly well.' },
      { question: 'Should my grooming business name include the type of pets I groom?', answer: 'If you specialize (dogs only, cats only, exotic pets), including that in your name helps attract the right clients and improves SEO. If you groom all pets, keeping it general allows for more flexibility.' },
      { question: 'Are puns and wordplay good for pet business names?', answer: 'Pet businesses are one of the few industries where puns are genuinely effective. Names that make owners smile ("Bark Avenue," "The Groom Room," "Pawsitively Clean") create emotional connections and are very shareable on social media.' },
      { question: 'Should I brand my mobile pet grooming differently than a brick-and-mortar salon?', answer: 'Mobile grooming businesses benefit from names that emphasize convenience and coming to the client ("Mobile Paws," "Grooming on the Go"). Salon-based businesses can focus more on the luxurious experience.' },
    ],
  },
  'event-planning': {
    slug: 'event-planning',
    name: 'event-planning',
    displayName: 'Event Planning',
    descriptors: ['premier', 'elegance', 'bloom', 'golden', 'vivid', 'stellar', 'luxury', 'curate', 'celebrate', 'dream'],
    nouns: ['events', 'planning', 'celebrations', 'productions', 'coordination', 'management', 'company'],
    suffixes: ['Co', 'LLC', 'Group', 'Productions', 'Events', 'Creative'],
    intro: 'Event planning business names should convey sophistication, creativity, and the promise of seamless, memorable experiences. Whether you specialize in weddings, corporate events, birthday parties, or large-scale productions, your business name will appear on everything from venue proposals to social media to word-of-mouth referrals. The best event planning names create an aspirational image — they make potential clients feel like their event will be extraordinary. Words like "elegance," "premier," "curated," and "stellar" signal high-quality execution. For wedding planners specifically, romantic and graceful imagery works well, while corporate event planners benefit from more professional, polished names.',
    examples: ['Premier Celebrations Co', 'Bloom Event Productions', 'Golden Hour Events', 'Stellar Planning Group', 'Dream Curated Events'],
    faqs: [
      { question: 'What makes a good event planning company name?', answer: 'Event planning names should inspire confidence and excitement. Words that suggest luxury, creativity, and flawless execution work best. Your name should make potential clients feel their event will be extraordinary and stress-free.' },
      { question: 'Should event planners specialize their name by event type?', answer: 'Specializing (wedding planning, corporate events, birthday parties) in your name helps attract the right clients and improves SEO. However, a general name allows you to accept any event type without confusing your brand.' },
      { question: 'How important are Instagram and Pinterest for event planning businesses?', answer: 'Extremely important — visual social platforms are primary marketing channels for event planners. Ensure your business name translates into a clean, consistent handle across Instagram, Pinterest, and TikTok.' },
      { question: 'Should event planners use their own name?', answer: 'Many wedding planners use their names for personal brand recognition, as clients often select planners based on personality and style fit. A separate brand name works better for larger firms with multiple coordinators.' },
    ],
  },
  landscaping: {
    slug: 'landscaping',
    name: 'landscaping',
    displayName: 'Landscaping',
    descriptors: ['green', 'verdant', 'bloom', 'earth', 'roots', 'grove', 'fresh', 'harvest', 'natural', 'terrain'],
    nouns: ['landscaping', 'garden', 'grounds', 'lawn', 'outdoors', 'landscape', 'yard', 'turf', 'outdoor'],
    suffixes: ['Co', 'LLC', 'Services', 'Group', 'Professionals', '& Sons'],
    intro: 'A landscaping business name should evoke natural beauty, expertise, and the transformation of outdoor spaces. Whether you offer lawn maintenance, landscape design, hardscaping, tree service, or irrigation, your business name is on your trucks, uniforms, and yard signs in every neighborhood you serve — it\'s both an advertisement and a trust signal. The best landscaping company names use natural imagery: words like "green," "verdant," "bloom," "roots," and "grove" immediately communicate the business and create a pleasant visual association. Consider your specialty and target market — residential lawn care requires a different name personality than high-end landscape design or commercial grounds maintenance.',
    examples: ['GreenGrove Landscaping', 'Verdant Earth Co', 'Bloom & Roots Grounds', 'Natural Terrain Services', 'Fresh Cut Lawn LLC'],
    faqs: [
      { question: 'What should a landscaping company name communicate?', answer: 'A landscaping name should communicate professionalism, reliability, and a love of the outdoors. Natural imagery (green, bloom, roots) makes the service immediately clear and creates positive associations.' },
      { question: 'Should I include my specialty in my landscaping company name?', answer: 'If you specialize in a specific area (irrigation, hardscaping, lawn care, landscape design), mentioning it helps attract the right clients. General landscaping companies benefit from broader names.' },
      { question: 'How important is truck signage for landscaping company names?', answer: 'Extremely important — your trucks are mobile billboards in every neighborhood you serve. A short, visually clear name that works well in logo form is essential. Avoid names that are hard to read at highway speed.' },
      { question: 'Are location-based names good for landscaping companies?', answer: 'Yes — local landscaping is an inherently geographic business. Including your city, county, or region in your name signals local expertise and helps with local SEO when homeowners search for landscapers in their area.' },
    ],
  },
  tutoring: {
    slug: 'tutoring',
    name: 'tutoring',
    displayName: 'Tutoring',
    descriptors: ['bright', 'smart', 'learn', 'achieve', 'excel', 'spark', 'grow', 'flourish', 'sharp', 'rise'],
    nouns: ['tutoring', 'learning', 'education', 'academy', 'scholars', 'prep', 'success', 'minds', 'skills'],
    suffixes: ['Co', 'Academy', 'Center', 'Hub', 'Group', 'Learning'],
    intro: 'A tutoring business name should inspire confidence in parents and students while communicating academic excellence and personalized support. Whether you specialize in test prep (SAT, ACT, GRE), subject tutoring (math, reading, science), or offer comprehensive academic coaching, your name will appear in parent Facebook groups, school bulletin boards, and local Google searches. The best tutoring business names use words that evoke achievement and potential: "bright," "achieve," "excel," "flourish," and "scholars" all suggest success. Consider your target age group and subjects — an elementary reading tutor has different naming needs than a college entrance exam prep specialist.',
    examples: ['BrightMinds Academy', 'Achieve Learning Hub', 'Excel Prep Center', 'Spark Scholars Co', 'Rise Education Group'],
    faqs: [
      { question: 'What words work well for tutoring business names?', answer: 'Words suggesting academic achievement and growth work best: bright, excel, achieve, flourish, spark, scholars, learn. Avoid generic names like "ABC Tutoring" that don\'t differentiate your service.' },
      { question: 'Should tutoring businesses include their specialty in the name?', answer: 'If you specialize in specific subjects or test prep, including it can attract your target clients directly. A math tutoring specialist benefits from having "math" in the name; a general academic tutor may prefer a broader name.' },
      { question: 'How should I name a tutoring business if I\'m a solo tutor?', answer: 'Solo tutors often use their name (e.g., "Sarah Johnson Tutoring") for personal brand building. As you scale, a business name like an academy or learning center sounds more established and professional.' },
      { question: 'Should a tutoring center use "academy" in the name?', answer: '"Academy" conveys a serious, professional commitment to education and works well for centers with multiple tutors and a curriculum. It may feel overly formal for a casual one-on-one tutoring setup.' },
    ],
  },
  'graphic-design': {
    slug: 'graphic-design',
    name: 'graphic-design',
    displayName: 'Graphic Design',
    descriptors: ['pixel', 'vector', 'bold', 'vivid', 'craft', 'design', 'visual', 'creative', 'sharp', 'ink'],
    nouns: ['design', 'studio', 'creative', 'visuals', 'graphics', 'branding', 'works', 'lab', 'co'],
    suffixes: ['Co', 'Studio', 'Creative', 'Labs', 'Works', 'Design'],
    intro: 'Your graphic design studio\'s name is itself a demonstration of your branding skills — potential clients will evaluate your name as a sample of your creative thinking. Whether you focus on brand identity, print design, UI/UX, illustration, or motion graphics, your studio name sets the creative tone for every client relationship. The best design studio names balance creative ambiguity with professional clarity. Names like "pixel," "vector," "vivid," and "craft" hint at the visual nature of your work without being too literal. Consider whether you want a name that reflects your personal aesthetic, your process, or your results. A minimalist design studio and an expressive illustrative studio warrant very different naming approaches.',
    examples: ['Pixel Craft Studio', 'Vivid Creative Co', 'Bold Ink Design', 'VectorWorks Creative', 'Sharp Visual Lab'],
    faqs: [
      { question: 'Should a graphic design business use the designer\'s name?', answer: 'Many successful designers build studios around their personal name (e.g., "Michael Bierut Design"). It works well for reputation-based work. A separate studio name is better for building a team or focusing on specific niches.' },
      { question: 'What does a great design studio name say about the business?', answer: 'A great design studio name communicates creativity, expertise, and personality. It should be a brand in itself — distinctive, memorable, and reflect your aesthetic. If your name isn\'t doing that, potential clients may question whether you can do it for them.' },
      { question: 'Should I include "design" or "creative" in my studio name?', answer: 'Including "design," "creative," or "studio" helps with discoverability. However, the most distinctive agency names stand alone — "Pentagram," "Landor," "IDEO" don\'t describe what they do yet are instantly recognizable.' },
      { question: 'How important is a portfolio website for a design business?', answer: 'A portfolio website is your most important marketing tool — more than your business name. Ensure your domain matches or closely relates to your business name for consistency and brand recognition.' },
    ],
  },
  'e-commerce': {
    slug: 'e-commerce',
    name: 'e-commerce',
    displayName: 'E-Commerce',
    descriptors: ['swift', 'shop', 'cart', 'click', 'deal', 'market', 'trade', 'sell', 'direct', 'prime'],
    nouns: ['shop', 'store', 'market', 'commerce', 'mart', 'hub', 'outlet', 'goods', 'bazaar'],
    suffixes: ['.com', 'Co', 'Shop', 'Store', 'Market', 'Hub'],
    intro: 'Naming your e-commerce business requires thinking like a digital brand from day one. Unlike brick-and-mortar stores, your name needs to work flawlessly online — as a domain name, social media handle, app name, and search keyword. The best e-commerce brand names are short, memorable, and directly searchable. Whether you\'re selling niche handmade goods, dropshipping general merchandise, or launching a D2C brand, your store name will appear in Google Ads, social media, and customer referrals. Domain availability is the first filter for e-commerce names — if the .com isn\'t available, reconsider the name. Great e-commerce names are often invented words (Amazon, Etsy, Zappos) or simple descriptive names that tell customers exactly what you sell.',
    examples: ['SwiftShop Market', 'ClickDeal Store Co', 'DirectGoods Hub', 'PrimeMart Commerce', 'QuickCart Outlet'],
    faqs: [
      { question: 'What makes a good e-commerce store name?', answer: 'A great e-commerce name is short, searchable, easy to spell, and available as a .com domain. It should be memorable enough that customers can find you again without searching for you specifically.' },
      { question: 'How important is the domain name for e-commerce?', answer: 'The domain name is your most critical branding decision for e-commerce. A .com is strongly preferred. If you can\'t get the exact match, try minor variations before settling for a different TLD.' },
      { question: 'Should e-commerce stores describe their products in their name?', answer: 'Niche stores benefit from descriptive names (e.g., "The Candle Shop") for SEO and immediate customer understanding. Lifestyle brands often use more abstract names that create aspiration and allow for product line expansion.' },
      { question: 'How does an e-commerce name affect SEO?', answer: 'Your store name influences branded search volume and brand recall. A unique, memorable name makes it easier to rank for branded searches. Including relevant keywords in your tagline and product descriptions matters more for non-branded SEO.' },
    ],
  },
};

export const INDUSTRY_LIST = Object.values(INDUSTRIES);
export const INDUSTRY_SLUGS = Object.keys(INDUSTRIES);
