import type { Metadata } from 'next';
import Container from '@/components/layout/Container';
import { toolMetadata } from '@/lib/seo';

export const metadata: Metadata = toolMetadata({
  title: 'Terms of Service',
  description: 'Utulio Terms of Service — the rules and conditions for using our free online tools.',
  path: '/terms',
});

export default function TermsPage() {
  return (
    <Container className="py-16 md:py-24">
      <div className="mx-auto max-w-2xl">
        <h1 className="mb-2 text-4xl font-bold tracking-tight text-zinc-900">Terms of Service</h1>
        <p className="mb-8 text-sm text-zinc-500">Last updated: January 1, 2026</p>

        <div className="space-y-8 text-zinc-600 leading-relaxed">
          <section>
            <h2 className="mb-3 text-xl font-semibold text-zinc-900">1. Acceptance of Terms</h2>
            <p>
              By accessing and using Utulio (utulio.com), you agree to be bound by these Terms of
              Service. If you do not agree to these terms, please do not use our Site.
            </p>
          </section>

          <section>
            <h2 className="mb-3 text-xl font-semibold text-zinc-900">2. Use of Tools</h2>
            <p>
              Utulio provides free online tools for personal and commercial use. You may use our
              tools for any lawful purpose. You agree not to:
            </p>
            <ul className="mt-3 list-disc space-y-1 pl-5">
              <li>Use the tools for any illegal or unauthorized purpose</li>
              <li>Attempt to reverse engineer, decompile, or disassemble any part of the Site</li>
              <li>Use automated tools to scrape or overload our servers</li>
              <li>
                Transmit malicious code or interfere with the proper functioning of the Site
              </li>
            </ul>
          </section>

          <section>
            <h2 className="mb-3 text-xl font-semibold text-zinc-900">3. Disclaimer of Warranties</h2>
            <p>
              Our tools are provided &quot;as is&quot; and &quot;as available&quot; without any
              warranties of any kind, express or implied. We do not warrant that the tools will be
              error-free, accurate, or uninterrupted. Use our tools at your own risk.
            </p>
            <p className="mt-3">
              Specifically, output from our tools (rates, invoices, passwords, business names,
              word counts) is provided for informational purposes only and should not be considered
              professional financial, legal, or security advice. Always verify critical outputs with
              a qualified professional.
            </p>
          </section>

          <section>
            <h2 className="mb-3 text-xl font-semibold text-zinc-900">
              4. Limitation of Liability
            </h2>
            <p>
              Utulio shall not be liable for any indirect, incidental, special, consequential, or
              punitive damages arising from your use of our tools. Our total liability shall not
              exceed $0, as our tools are provided free of charge.
            </p>
          </section>

          <section>
            <h2 className="mb-3 text-xl font-semibold text-zinc-900">5. Intellectual Property</h2>
            <p>
              The Utulio website, including its design, code, and content, is owned by Utulio.
              You may not copy, reproduce, or distribute any part of the Site without our written
              permission. Output generated by our tools (invoices, business names, passwords) is
              yours to use freely.
            </p>
          </section>

          <section>
            <h2 className="mb-3 text-xl font-semibold text-zinc-900">6. Third-Party Links</h2>
            <p>
              Our Site may contain links to third-party websites (such as domain registrars for
              checking business name availability). We are not responsible for the content or
              privacy practices of those sites.
            </p>
          </section>

          <section>
            <h2 className="mb-3 text-xl font-semibold text-zinc-900">7. Modifications</h2>
            <p>
              We reserve the right to modify or discontinue any tool or the entire Site at any
              time without notice. We may also update these Terms from time to time. Continued use
              of the Site after changes constitutes acceptance of the updated Terms.
            </p>
          </section>

          <section>
            <h2 className="mb-3 text-xl font-semibold text-zinc-900">8. Governing Law</h2>
            <p>
              These Terms shall be governed by and construed in accordance with applicable law.
              Any disputes shall be resolved through binding arbitration or in a court of competent
              jurisdiction.
            </p>
          </section>

          <section>
            <h2 className="mb-3 text-xl font-semibold text-zinc-900">9. Contact</h2>
            <p>
              Questions about these Terms? Contact us at{' '}
              <a
                href="mailto:hello@utulio.com"
                className="text-zinc-900 underline underline-offset-2"
              >
                hello@utulio.com
              </a>
              .
            </p>
          </section>
        </div>
      </div>
    </Container>
  );
}
